// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class GenerateMarchingCubeKeys
    {
        public static readonly ValueParameterKey<uint> SizeX = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> SizeY = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> SizeZ = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<float> isoLevel = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<int> maxTriangles = ParameterKeys.NewValue<int>();
        public static readonly ObjectParameterKey<Buffer> edges = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> triangulation = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> points = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> triangles = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> trianglesCount = ParameterKeys.NewObject<Buffer>();
    }
}
